export const Colors = {
  background: '#fff',
  boardBackground: '#ddd',
  cellBackground: '#fff',
  cellBorder: '#ccc',
  fixedText: '#888',
  numberText: '#000',
  highlightBorder: '#fc0',
  highlightText: '#c90',
  hintText: 'darkturquoise',
  glowBorder: 'darkturquoise',
  glowText: 'darkturquoise',
  errorBorder: 'red',
  finishedBackground: '#fc0',
  padText: '#333',
  padProgress: '#999',
  timerText: '#6b6b6b',
  infoBackground: '#f2f2f2',
  accent: '#fc0',
  disabled: 0.5,
};
